/* ============================================
   Güncel Acil Tıp Literatürü — Veri Dosyası
   Bu dosya her sabah otomatik güncellenir. Kaynak: PubMed (açık künye + DOI).
   Özetler Türkçe'ye uyarlanmıştır; tam metin gösterilmez, her kart orijinal kaynağa yönlendirir.
   Son güncelleme: 2026-07-12
   ============================================ */
window.MAKALELER = {
  guncelleme_iso: "2026-07-12",
  guncelleme_tr: "12 Temmuz 2026",
  makaleler: [
    {
      baslik: "Çok Düşük Riskli Minör Kafa Travmalı Çocuklarda BT Kullanımıyla İlişkili Hekim Özellikleri",
      baslik_en: "Clinician characteristics associated with CT use in children with minor blunt head trauma at very low risk for clinically important traumatic brain injuries",
      dergi: "Emerg Med J",
      tarih: "10 Tem 2026",
      tarih_iso: "2026-07-10",
      kategori: "pediatri",
      kategori_etiket: "Pediatrik Acil",
      tur: "Araştırma",
      ozet: "Çok merkezli prospektif çalışmada, PECARN kuralına göre çok düşük riskli 8957 çocuğun %7.3'üne yine de BT çekildi; daha fazla deneyim yılı, düşük risk toleransı ve pratikte az sayıda çocuk görmek gereksiz BT istemiyle ilişkili bulundu.",
      yazarlar: "Chaudhari PP ve ark.",
      doi: "10.1136/emermed-2025-215859",
      link: "https://doi.org/10.1136/emermed-2025-215859"
    },
    {
      baslik: "Acil Sağlık Hizmetleri Personelinde Tükenmişlik Yaygınlığı ve İlişkili Faktörler: Meta-Analiz",
      baslik_en: "Prevalence of burnout and associated moderator factors among emergency medical services personnel: a meta-analysis",
      dergi: "Eur J Emerg Med",
      tarih: "9 Tem 2026",
      tarih_iso: "2026-07-09",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Meta-Analiz",
      ozet: "35 çalışma ve 32.841 acil sağlık (EMS) çalışanını kapsayan meta-analizde havuzlanmış tükenmişlik yaygınlığı %40 bulundu; en yüksek oran karma EMS personelinde (%52), ardından paramediklerde (%41) saptandı.",
      yazarlar: "Huang G ve ark.",
      doi: "10.1097/MEJ.0000000000001359",
      link: "https://doi.org/10.1097/MEJ.0000000000001359"
    },
    {
      baslik: "Nitazen Aşırı Dozlarında Yüksek Doz Nalokson Gerekli mi?",
      baslik_en: "Are high doses of naloxone required for nitazene overdoses?",
      dergi: "Emerg Med J",
      tarih: "9 Tem 2026",
      tarih_iso: "2026-07-09",
      kategori: "toksikoloji",
      kategori_etiket: "Toksikoloji",
      tur: "Derleme",
      ozet: "Beş çalışmayı içeren derlemede, yeni sentetik opioid nitazenin aşırı dozunu geri çevirmek için 0.4-4.40 mg nalokson aralığının yeterli olduğu; rutin olarak daha yüksek dozları destekleyen kanıt bulunmadığı bildirildi.",
      yazarlar: "Blanksby I ve Harrison L",
      doi: "10.1136/emermed-2026-216211",
      link: "https://doi.org/10.1136/emermed-2026-216211"
    },
    {
      baslik: "İntranazal Ketamin Çocuklarda Yeterli Prosedürel Sedasyon Sağlayabilir mi?",
      baslik_en: "Is there evidence that intranasal ketamine can provide adequate procedural sedation in paediatric patients?",
      dergi: "Emerg Med J",
      tarih: "9 Tem 2026",
      tarih_iso: "2026-07-09",
      kategori: "pediatri",
      kategori_etiket: "Pediatrik Acil",
      tur: "Derleme",
      ozet: "Sekiz çalışmalık derlemede intranazal ketaminin başarı olasılığı intravenöz yola göre bir miktar düşük bulunsa da, ağır iğne korkusu olan çocuklarda iğnesiz bir seçenek olarak değerlendirilebileceği belirtildi.",
      yazarlar: "Jeyabelen H ve Manak I",
      doi: "10.1136/emermed-2026-216136",
      link: "https://doi.org/10.1136/emermed-2026-216136"
    },
    {
      baslik: "Yeni Bir Acil Servis Psikiyatrik Bakım Modelinin Kalış Süresini Azaltmadaki Etkinliği",
      baslik_en: "Effectiveness of a Novel Emergency Department Psychiatric Care Model in Reducing Length of Stay",
      dergi: "Ann Emerg Med",
      tarih: "8 Tem 2026",
      tarih_iso: "2026-07-08",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Araştırma",
      ozet: "Kesintili zaman serisi çalışmasında acil servise 7/24 gömülü psikiyatri ekibi modeli, psikiyatrik hastalarda medyan kalış süresini 8.35 saatten 5.61 saate indirdi; en belirgin azalma istemsiz (hold) hastalarda görüldü.",
      yazarlar: "Hewlett MM ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.008",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.008"
    },
    {
      baslik: "CASPER Skoru: Kalp Durması Sonrası Koroner Darlığı Belirlemek İçin Yapay Zeka-EKG Temelli Yatak Başı Araç",
      baslik_en: "Development of the CASPER-Score: A bedside tool integrating AI-based ECG analysis with key clinical predictors to identify relevant coronary artery stenosis in patients after out-of-hospital cardiac arrest",
      dergi: "Resuscitation",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "kardiyoloji",
      kategori_etiket: "Kardiyoloji",
      tur: "Araştırma",
      ozet: "204 hastalık retrospektif kohortta yaş, erkek cinsiyet, şoklanabilir ritim ve yapay zeka EKG ile OMİ saptanmasından oluşan CASPER Skoru, hastane dışı kalp durması sonrası anlamlı koroner arter darlığını 0.86 AUC ile öngördü.",
      yazarlar: "von Beck LM ve ark.",
      doi: "10.1016/j.resuscitation.2026.111198",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111198"
    },
    {
      baslik: "Acil Serviste Geçirilen Süre ile 30 Günlük Mortalite İlişkisi: İngiltere'de Toplum Düzeyinde Gözlemsel Çalışma",
      baslik_en: "Association Between Time Spent in the Emergency Department and 30-Day Mortality: A Population-Level Observational Study in England",
      dergi: "Ann Emerg Med",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Araştırma",
      ozet: "6.7 milyon acil servis ziyaretini kapsayan çalışmada, 2 saate kıyasla 12 saat kalanlarda taburculuk/yatış sonrası 30 günlük ölüm olasılığı 2.1 kat yüksek bulundu; ancak yazarlar bunun nedensellikten çok artık karıştırıcılığı yansıtabileceğini vurguladı.",
      yazarlar: "Aston H ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.017",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.017"
    },
    {
      baslik: "Hastane Öncesi İnme Yönlendirmesine Hastane Performansının Dahil Edilmesi: Simülasyon Çalışması",
      baslik_en: "Inclusion of Hospital Performance in Prehospital Stroke Routing: A Simulation Study",
      dergi: "Prehosp Emerg Care",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "noroloji",
      kategori_etiket: "Nöroloji",
      tur: "Simülasyon Çalışması",
      ozet: "400.000 senaryolu simülasyonda, hastane kapı-iğne ve kapı-ponksiyon sürelerinin eklenmesi önerilen inme hedef hastanesini vakaların %63'ünde AHA konsensüs önerilerinden farklılaştırdı; hastalar daha hızlı reperfüzyon sağlayan merkezlere yönlendirildi.",
      yazarlar: "Zachrison KS ve ark.",
      doi: "10.1080/10903127.2026.2689666",
      link: "https://doi.org/10.1080/10903127.2026.2689666"
    },
    {
      baslik: "Uyanık Travmatik Spinal Kord Yaralanmalı Hastaların Yönetiminde İngiltere HEMS Klinisyenlerinin Zorlukları",
      baslik_en: "Challenges faced by UK HEMS clinicians when managing awake patients with traumatic spinal cord injuries: a cross-sectional survey",
      dergi: "Emerg Med J",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "travma",
      kategori_etiket: "Travma",
      tur: "Anket Çalışması",
      ozet: "16 HEMS servisinden 62 klinisyenle yapılan kesitsel ankette, uyanık spinal kord yaralanmalı hastalarda iletişim ve psikolojik yük (özellikle prognoz sorularının yanıtlanması) hemodinamik yönetimden daha zorlayıcı olarak değerlendirildi.",
      yazarlar: "Symes M ve ark.",
      doi: "10.1136/emermed-2025-215481",
      link: "https://doi.org/10.1136/emermed-2025-215481"
    },
    {
      baslik: "Umbilikal Arter pH'sı, Yenidoğan Kalp Hızı ve Doğumda Ventilasyon İlişkisi: Prospektif Gözlemsel Çalışma",
      baslik_en: "The relationship between umbilical arterial pH, newborn heart rate and ventilation at birth - a prospective observational study",
      dergi: "Resuscitation",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "3662 yenidoğanda umbilikal arter pH'sı ile 1. dakika kalp hızı arasında anlamlı doğrusal ilişki saptanmadı; pH<7.00 olanların yalnızca yarısında bradikardi görülürken, Apgar skorları doğum asfiksisinin derecesini iyi yansıttı.",
      yazarlar: "Rettedal S ve ark.",
      doi: "10.1016/j.resuscitation.2026.111197",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111197"
    },
    {
      baslik: "Acil Serviste Evsiz Bireylerde Hepatit C Taraması: DETECT Hep C Çalışmasının İkincil Analizi",
      baslik_en: "Hepatitis C Screening Among Persons Experiencing Homelessness in the Emergency Department: A Secondary Analysis of the DETECT for Hepatitis C Screening Trial",
      dergi: "Ann Emerg Med",
      tarih: "6 Tem 2026",
      tarih_iso: "2026-07-06",
      kategori: "enfeksiyon",
      kategori_etiket: "Enfeksiyon",
      tur: "Araştırma",
      ozet: "67.223 ziyaretlik ikincil analizde evsiz bireyler hedefsiz HCV taramasını barınan hastalardan daha sık kabul etti ve HCV seropozitiflik ile viremi riski 2-3 kat yüksek bulundu; hedefsiz tarama bu grupta olguları yakalamada daha etkili göründü.",
      yazarlar: "Joseph KM ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.009",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.009"
    },
    {
      baslik: "KOAH Alevlenmelerinde Acil Servis Taburculuğu İçin Roth ve Dispne Şiddet Skorunun Değerlendirilmesi",
      baslik_en: "Evaluating the Roth and Dyspnea severity score for emergency department discharge in exacerbations of chronic obstructive pulmonary disease",
      dergi: "Am J Emerg Med",
      tarih: "6 Tem 2026",
      tarih_iso: "2026-07-06",
      kategori: "klinik-karar",
      kategori_etiket: "Klinik Karar",
      tur: "Tanısal Doğruluk Çalışması",
      ozet: "Türkiye'de dört merkezde 352 KOAH alevlenmesi hastasıyla yürütülen çalışmada, taburculuk kararı için Roth skoru (AUC 0.894) ve Dispne Şiddet Skoru (AUC 0.917) yüksek duyarlılık gösterdi; hızlı ve non-invaziv yatak başı araçlar olarak öne çıktı.",
      yazarlar: "Yazıcı MM ve ark.",
      doi: "10.1016/j.ajem.2026.07.007",
      link: "https://doi.org/10.1016/j.ajem.2026.07.007"
    },
    {
      baslik: "Hastane Dışı Kalp Durmalarında Uygulayıcı Kategorisine Göre KPR Alımında Cinsiyet Eşitsizlikleri",
      baslik_en: "Analyses of gender disparities in receipt of bystander cardiopulmonary resuscitation after out-of-hospital cardiac arrests by patient's age group and bystander category",
      dergi: "Resuscitation",
      tarih: "5 Tem 2026",
      tarih_iso: "2026-07-05",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "Japonya ulusal kayıt sisteminden 453.441 tanıklı kalp durması olgusunda, KPR alımını belirlemede cinsiyetten çok uygulayıcı kategorisi öne çıktı; tanık arkadaş, meslektaş veya yoldan geçen olduğunda kadınlar tüm yetişkin yaş gruplarında daha az KPR aldı.",
      yazarlar: "Fukui K ve ark.",
      doi: "10.1016/j.resuscitation.2026.111201",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111201"
    },
    {
      baslik: "Kardiyopulmoner Resüsitasyon Sırasında Volüm Kontrollü Mekanik Ventilasyon: Sistematik Derleme ve Meta-Analiz",
      baslik_en: "Volume-controlled mechanical ventilation during cardiopulmonary resuscitation: A systematic review and meta-analysis",
      dergi: "Resuscitation",
      tarih: "3 Tem 2026",
      tarih_iso: "2026-07-03",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Sistematik Derleme ve Meta-Analiz",
      ozet: "13 çalışmayı (6 randomize, 461 hasta) içeren derlemede, KPR sırasında volüm kontrollü mekanik ventilasyon ile manuel ventilasyon arasında spontan dolaşımın geri dönüşü açısından anlamlı fark bulunmadı; kanıt kesinliği çok düşük-düşük düzeyde değerlendirildi.",
      yazarlar: "Wittig J ve ark.",
      doi: "10.1016/j.resuscitation.2026.111199",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111199"
    },
    {
      baslik: "Hastane Öncesi Pediatrik Kan Transfüzyonu Programları İçin En Uygun Hedef Hasta ve EMS Birimlerinin Tanımlanması",
      baslik_en: "Characterizing pediatric trauma patients and EMS agencies that are optimal targets for prehospital pediatric blood transfusion programs",
      dergi: "Prehosp Emerg Care",
      tarih: "2 Tem 2026",
      tarih_iso: "2026-07-02",
      kategori: "travma",
      kategori_etiket: "Travma",
      tur: "Araştırma",
      ozet: "NEMSIS 2021-2024 verisinde 2.49 milyon yaralı çocuk kaydının %1.37'si transfüzyon kriterlerini karşıladı, ancak yalnızca %1.01'ine kan verildi; uygun hastaların büyük çoğunluğuna ileri yaşam desteği düzeyindeki birimler baktı.",
      yazarlar: "Ramgopal S ve Martin-Gill C",
      doi: "10.1080/10903127.2026.2696013",
      link: "https://doi.org/10.1080/10903127.2026.2696013"
    }
  ]
};
