/* ============================================
   Güncel Acil Tıp Literatürü — Veri Dosyası
   Bu dosya her sabah otomatik güncellenir. Kaynak: PubMed (açık künye + DOI).
   Özetler Türkçe'ye uyarlanmıştır; tam metin gösterilmez, her kart orijinal kaynağa yönlendirir.
   Son güncelleme: 2026-07-14
   ============================================ */
window.MAKALELER = {
  guncelleme_iso: "2026-07-14",
  guncelleme_tr: "14 Temmuz 2026",
  makaleler: [
    {
      baslik: "Hemorajik Şokta Doğurganlık Çağındaki Kadınlarda RhD-Pozitif Transfüzyon: Risk, Gerçek ve Politika",
      baslik_en: "RhD-Positive Transfusion in Females of Childbearing Potential in Hemorrhagic Shock: Risk, Reality, and Policy",
      dergi: "Prehosp Emerg Care",
      tarih: "13 Tem 2026",
      tarih_iso: "2026-07-13",
      kategori: "travma",
      kategori_etiket: "Travma",
      tur: "Derleme",
      ozet: "RhD-negatif ürün bulunmadığında doğurganlık çağındaki kadınlara RhD-pozitif kan verilmesini inceleyen bu derlemede, modelleme çalışmaları anti-D kaynaklı fetal ölüm riskini maruz kalanların %0.1'inden azı olarak öngörüyor. Yazarlar, hastane öncesi transfüzyon politikalarının bu risk-yarar dengesini yansıtmasını ve travma hastalarına erişimi kısıtlamamasını savunuyor.",
      yazarlar: "Murphy TO ve ark.",
      doi: "10.1080/10903127.2026.2701877",
      link: "https://doi.org/10.1080/10903127.2026.2701877"
    },
    {
      baslik: "Hastane Dışı Kardiyak Arrest Sonrası Çocuklarda Enfeksiyonların Değerlendirilmesi",
      baslik_en: "Characterizing Infections in Children after Out-of-Hospital Cardiac Arrest",
      dergi: "Resuscitation",
      tarih: "11 Tem 2026",
      tarih_iso: "2026-07-11",
      kategori: "pediatri",
      kategori_etiket: "Pediatrik Acil",
      tur: "Araştırma",
      ozet: "Tek merkezli retrospektif kohortta, hastane dışı arrest sonrası yoğun bakıma alınan 203 çocuğun %20'sinde ilk 48 saatte kesin ya da olası bakteriyel enfeksiyon saptandı. Bu çocuklarda KPR süresi daha uzun (medyan 24'e karşı 10 dakika) ve taburculuğa sağkalım daha düşüktü (%33'e karşı %70).",
      yazarlar: "Cramer SL ve ark.",
      doi: "10.1016/j.resuscitation.2026.111204",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111204"
    },
    {
      baslik: "Çok Düşük Riskli Minör Künt Kafa Travmalı Çocuklarda BT Kullanımıyla İlişkili Klinisyen Özellikleri",
      baslik_en: "Clinician characteristics associated with CT use in children with minor blunt head trauma at very low risk for clinically important traumatic brain injuries",
      dergi: "Emerg Med J",
      tarih: "10 Tem 2026",
      tarih_iso: "2026-07-10",
      kategori: "pediatri",
      kategori_etiket: "Pediatrik Acil",
      tur: "Araştırma",
      ozet: "PECARN kuralına göre klinik olarak önemli travmatik beyin hasarı açısından çok düşük riskli 8.957 çocuğun %7.3'üne BT çekildi. Çok değişkenli analizde daha fazla deneyim yılı, pratiğinde çocuk oranının %50'nin altında olması ve belirsiz sonuçlardan kaçınma eğilimi gereksiz BT istemiyle ilişkiliydi.",
      yazarlar: "Chaudhari PP ve ark.",
      doi: "10.1136/emermed-2025-215859",
      link: "https://doi.org/10.1136/emermed-2025-215859"
    },
    {
      baslik: "Acil Sağlık Hizmetleri Personelinde Tükenmişlik Sıklığı ve İlişkili Düzenleyici Faktörler: Meta-analiz",
      baslik_en: "Prevalence of burnout and associated moderator factors among emergency medical services personnel: a meta-analysis",
      dergi: "Eur J Emerg Med",
      tarih: "9 Tem 2026",
      tarih_iso: "2026-07-09",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Meta-analiz",
      ozet: "32.841 acil sağlık çalışanını kapsayan 35 çalışmanın meta-analizinde havuzlanmış tükenmişlik sıklığı %40 (%95 GA 33-49) bulundu; ancak çalışmalar arası değişkenlik yüksekti (%95 öngörü aralığı 9-82). En yüksek oran karma ekiplerde (%52), en düşük itfaiyecilerdeydi (%19).",
      yazarlar: "Huang G ve ark.",
      doi: "10.1097/MEJ.0000000000001359",
      link: "https://doi.org/10.1097/MEJ.0000000000001359"
    },
    {
      baslik: "Nitazen Aşırı Dozunda Yüksek Doz Nalokson Gerekli mi?",
      baslik_en: "Are high doses of naloxone required for nitazene overdoses?",
      dergi: "Emerg Med J",
      tarih: "9 Tem 2026",
      tarih_iso: "2026-07-09",
      kategori: "toksikoloji",
      kategori_etiket: "Toksikoloji",
      tur: "Derleme",
      ozet: "Beş uygun çalışmayı değerlendiren bu kanıt derlemesi, nitazen aşırı dozunun tedavisinde 0.4-4.40 mg aralığında nalokson dozlarının yeterli olduğunu bildiriyor. Bulgular rutin olarak daha yüksek dozların kullanılmasını desteklemiyor; doz sıklığının etkisi için ileri araştırma gerekiyor.",
      yazarlar: "Blanksby I, Harrison L",
      doi: "10.1136/emermed-2026-216211",
      link: "https://doi.org/10.1136/emermed-2026-216211"
    },
    {
      baslik: "Acil Serviste Tanı Konulan Dietilen Glikol Zehirlenmesi: Olgu Sunumu",
      baslik_en: "Diethylene glycol poisoning identified in the emergency department: A case report",
      dergi: "Am J Emerg Med",
      tarih: "8 Tem 2026",
      tarih_iso: "2026-07-08",
      kategori: "toksikoloji",
      kategori_etiket: "Toksikoloji",
      tur: "Olgu Sunumu",
      ozet: "Fren hidroliğinin kasıtlı içilmesine bağlı dietilen glikol toksisitesi gelişen ve hemodiyalizle tedavi edilen bir olgu sunuluyor; tedavi sonrası ölçülen DEG düzeyinde belirgin düşüş izlendi. Olgu, toksik alkol şüphesinde erken tanınma ve ampirik tedavinin önemini vurguluyor.",
      yazarlar: "Ruggieri J ve ark.",
      doi: "10.1016/j.ajem.2026.07.011",
      link: "https://doi.org/10.1016/j.ajem.2026.07.011"
    },
    {
      baslik: "Yeni Bir Acil Servis Psikiyatrik Bakım Modelinin Kalış Süresini Azaltmadaki Etkinliği",
      baslik_en: "Effectiveness of a Novel Emergency Department Psychiatric Care Model in Reducing Length of Stay",
      dergi: "Ann Emerg Med",
      tarih: "8 Tem 2026",
      tarih_iso: "2026-07-08",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Araştırma",
      ozet: "Acil servise 7/24 psikiyatri alanında uzmanlaşmış hemşire ve destek personeli yerleştiren model sonrası 5.222 başvuruda medyan kalış süresi 8.35 saatten 5.61 saate indi (düzeltilmiş medyan fark -1.64 saat; %95 GA -3.15 ile -0.13). En büyük azalma istemsiz psikiyatrik tutma kararı verilen hastalarda görüldü.",
      yazarlar: "Hewlett MM ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.008",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.008"
    },
    {
      baslik: "CASPER Skorunun Geliştirilmesi: Arrest Sonrası Anlamlı Koroner Darlığı Belirlemek İçin Yapay Zeka Temelli EKG Analizi",
      baslik_en: "Development of the CASPER-Score: A bedside tool integrating AI-based ECG analysis with key clinical predictors to identify relevant coronary artery stenosis in patients after out-of-hospital cardiac arrest",
      dergi: "Resuscitation",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "kardiyoloji",
      kategori_etiket: "Kardiyoloji",
      tur: "Araştırma",
      ozet: "Koroner anjiyografi yapılan 204 hastane dışı arrest hastasının %77'sinde anlamlı koroner darlık saptandı. Yaş, erkek cinsiyet, şoklanabilir başlangıç ritmi ve yapay zeka temelli EKG ile oklüzyon miyokard enfarktüsü saptanmasından oluşan CASPER skoru iyi ayırt edicilik gösterdi (AUC 0.86).",
      yazarlar: "von Beck LM ve ark.",
      doi: "10.1016/j.resuscitation.2026.111198",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111198"
    },
    {
      baslik: "Almanya'da Ekstrakorporeal Kardiyopulmoner Resüsitasyonun Görünümü: Ulusal Retrospektif Çalışma",
      baslik_en: "The landscape of extracorporeal cardiopulmonary resuscitation in Germany. A nationwide retrospective study",
      dergi: "Prehosp Emerg Care",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "2018-2023 arasında konvansiyonel KPR'ye dirençli hastane dışı arrestle yatırılan 27.056 hastanın %2.9'una ECPR uygulandı; sağkalım ECPR ile %11.8, ECPR'siz %11.3 olup anlamlı fark yoktu. ECPR kullanımı %1.8'den %4.1'e çıkmasına rağmen sağkalım değişmedi ve merkez başına medyan yıllık olgu sayısı üçtü.",
      yazarlar: "Jasny T ve ark.",
      doi: "10.1080/10903127.2026.2697436",
      link: "https://doi.org/10.1080/10903127.2026.2697436"
    },
    {
      baslik: "Acil Serviste Geçirilen Süre ile 30 Günlük Mortalite İlişkisi: İngiltere'de Popülasyon Düzeyinde Gözlemsel Çalışma",
      baslik_en: "Association Between Time Spent in the Emergency Department and 30-Day Mortality: A Population-Level Observational Study in England",
      dergi: "Ann Emerg Med",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Araştırma",
      ozet: "Acil olmayan aciliyette başvuran 6.721.179 hastada, acil serviste 2 saat kalanlara kıyasla 12 saat kalanlarda taburculuk ya da yatış sonrası 30 günlük ölüm olasılığı 2.1 kat (%95 GA 2.02-2.28) yüksekti. Yazarlar, ilişkinin nedensel olmayabileceğini ve artık karıştırıcıları yansıtabileceğini vurguluyor.",
      yazarlar: "Aston H ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.017",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.017"
    },
    {
      baslik: "Hastane Öncesi İnme Yönlendirmesinde Hastane Performansının Dikkate Alınması: Simülasyon Çalışması",
      baslik_en: "Inclusion of Hospital Performance in Prehospital Stroke Routing: A Simulation Study",
      dergi: "Prehosp Emerg Care",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "noroloji",
      kategori_etiket: "Nöroloji",
      tur: "Araştırma",
      ozet: "400.000 hasta-konum senaryosunda, hastanelerin gerçek kapı-iğne ve kapı-ponksiyon sürelerini karar modeline eklemek, yönlendirmelerin %63.1'inde AHA uzlaşı önerilerinden farklı bir hastane seçilmesine yol açtı ve hastalar daha hızlı reperfüzyon sağlayan merkezlere yönlendirildi. İnme şiddeti ve büyük damar tıkanıklığı olasılığı arttıkça öneriler birbirine yaklaştı.",
      yazarlar: "Zachrison KS ve ark.",
      doi: "10.1080/10903127.2026.2689666",
      link: "https://doi.org/10.1080/10903127.2026.2689666"
    },
    {
      baslik: "Çok Bileşenli Bir Girişim Künt Kafa Travmasında Bilgisayarlı Tomografi Kullanımını Azaltıyor",
      baslik_en: "A multimodal intervention reduces computed tomography use in blunt head injury",
      dergi: "Am J Emerg Med",
      tarih: "6 Tem 2026",
      tarih_iso: "2026-07-06",
      kategori: "klinik-karar",
      kategori_etiket: "Klinik Karar",
      tur: "Araştırma",
      ozet: "NEXUS ya da Kanada BT kuralı arasında seçim sunan kılavuz, eğitim oturumları, aylık geri bildirim ve elektronik karar desteğinden oluşan girişim sonrası beyin BT istem olasılığı anlamlı azaldı (düzeltilmiş OR 0.91; %95 GA 0.89-0.94). Pozitif BT oranında, 72 saatlik geri dönüşlerde ve bu dönüşlerdeki pozitif BT oranında değişiklik saptanmadı.",
      yazarlar: "Berlyand Y ve ark.",
      doi: "10.1016/j.ajem.2026.07.005",
      link: "https://doi.org/10.1016/j.ajem.2026.07.005"
    },
    {
      baslik: "KOAH Alevlenmelerinde Acil Servisten Taburculuk Kararı İçin Roth ve Dispne Şiddet Skorunun Değerlendirilmesi",
      baslik_en: "Evaluating the Roth and Dyspnea severity score for emergency department discharge in exacerbations of chronic obstructive pulmonary disease",
      dergi: "Am J Emerg Med",
      tarih: "6 Tem 2026",
      tarih_iso: "2026-07-06",
      kategori: "klinik-karar",
      kategori_etiket: "Klinik Karar",
      tur: "Araştırma",
      ozet: "Türkiye'de dört merkezde yürütülen prospektif tanısal doğruluk çalışmasında, 352 KOAH alevlenmesi hastasında taburculuk kararı için Roth skoru AUC 0.894 (kesme 9.95 sn; duyarlılık %87.4, özgüllük %86.8) ve Dispne Şiddet Skoru AUC 0.917 (kesme 5; duyarlılık %88.9, özgüllük %79.5) ile yüksek doğruluk gösterdi. Yazarlar bunları hızlı ve non-invaziv yatak başı araçlar olarak öneriyor.",
      yazarlar: "Yazıcı MM ve ark.",
      doi: "10.1016/j.ajem.2026.07.007",
      link: "https://doi.org/10.1016/j.ajem.2026.07.007"
    },
    {
      baslik: "Acil Serviste Evsiz Bireylerde Hepatit C Taraması: DETECT Hep C Çalışmasının İkincil Analizi",
      baslik_en: "Hepatitis C Screening Among Persons Experiencing Homelessness in the Emergency Department: A Secondary Analysis of the DETECT for Hepatitis C Screening Trial",
      dergi: "Ann Emerg Med",
      tarih: "6 Tem 2026",
      tarih_iso: "2026-07-06",
      kategori: "enfeksiyon",
      kategori_etiket: "Enfeksiyon",
      tur: "Araştırma",
      ozet: "67.223 acil başvurusunun ikincil analizinde evsiz bireyler hedefsiz taramayı barınan hastalara göre daha sık kabul etti (düzeltilmiş RR 1.31; %95 GA 1.22-1.41). Her iki stratejide de evsizlik HCV seropozitifliği (aRR 2.91 ve 2.07) ve viremi ile ilişkiliydi; bu da hedefsiz taramanın bu grupta saptamayı artırabileceğini düşündürüyor.",
      yazarlar: "Joseph KM ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.009",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.009"
    },
    {
      baslik: "Hastane Dışı Kardiyak Arrestte Çevredeki Kişilerce KPR Uygulanmasındaki Cinsiyet Farklılıkları",
      baslik_en: "Analyses of gender disparities in receipt of bystander cardiopulmonary resuscitation after out-of-hospital cardiac arrests by patient's age group and bystander category",
      dergi: "Resuscitation",
      tarih: "5 Tem 2026",
      tarih_iso: "2026-07-05",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "Japonya ulusal kayıtlarındaki 453.441 tanıklı arrestte kadınlar genel olarak daha sık KPR alsa da, 15-64 yaş aralığında ve uygulayıcı arkadaş, iş arkadaşı ya da yoldan geçen olduğunda daha az KPR aldı. Uygulayıcı kategorisi (OR 3.56) KPR alınmasında hasta cinsiyetinden (OR 1.10) çok daha güçlü belirleyiciydi.",
      yazarlar: "Fukui K ve ark.",
      doi: "10.1016/j.resuscitation.2026.111201",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111201"
    },
    {
      baslik: "Hastane Dışı Kardiyak Arreste Müdahil Olan Kişilere Yönelik Destek Girişimleri: Kapsam Derlemesi",
      baslik_en: "A scoping review of Support Interventions for Bystanders involved in Out-of-Hospital Cardiac Arrest",
      dergi: "Resuscitation",
      tarih: "5 Tem 2026",
      tarih_iso: "2026-07-05",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Kapsam Derlemesi",
      ozet: "On altı yayın ve gri literatür taranarak arreste tanık olan ya da KPR uygulayan kişilere yönelik toplam 14 destek girişimi belirlendi; çoğu bilgilendirme ve debriefing içeriyordu. Yalnızca beş çalışma katılımcı sonucu bildirdi ve hiçbiri girişimlerin etkinliğini değerlendirmemişti.",
      yazarlar: "Sajjad U ve ark.",
      doi: "10.1016/j.resuscitation.2026.111202",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111202"
    }
  ]
};
