/* ============================================
   Güncel Acil Tıp Literatürü — Veri Dosyası
   Bu dosya her sabah otomatik güncellenir.
   Kaynak: PubMed (açık künye + DOI). Özetler Türkçe'ye uyarlanmıştır;
   tam metin gösterilmez, her kart orijinal kaynağa yönlendirir.
   Son güncelleme: 2026-07-08
   ============================================ */
window.MAKALELER = {
  guncelleme_iso: "2026-07-08",
  guncelleme_tr: "8 Temmuz 2026",
  makaleler: [
    {
      baslik: "Almanya'da Ekstrakorporeal Kardiyopulmoner Resüsitasyon (ECPR) Görünümü: Ulusal Retrospektif Çalışma",
      baslik_en: "The landscape of extracorporeal cardiopulmonary resuscitation in Germany. A nationwide retrospective study",
      dergi: "Prehosp Emerg Care",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "2018-2023 arasında dirençli hastane dışı kardiyak arrest nedeniyle hastaneye alınan 27.056 hastadan yalnızca 785'ine (%2,9) ECPR uygulanmış; ECPR alan ve almayanlarda sağkalım benzerdi (%11,8'e karşı %11,3). Kullanım %1,8'den %4,1'e yükselirken sağkalım yaklaşık %12'de sabit kalmış.",
      yazarlar: "Jasny T. ve ark.",
      doi: "10.1080/10903127.2026.2697436",
      link: "https://doi.org/10.1080/10903127.2026.2697436"
    },
    {
      baslik: "Acil Serviste Geçirilen Süre ile 30 Günlük Mortalite İlişkisi: İngiltere'de Toplum Düzeyinde Gözlemsel Çalışma",
      baslik_en: "Association Between Time Spent in the Emergency Department and 30-Day Mortality: A Population-Level Observational Study in England",
      dergi: "Ann Emerg Med",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Araştırma",
      ozet: "Acil olmayan aciliyetteki 6.721.179 hastanın incelendiği çalışmada, acil serviste 2 saat kalmaya kıyasla 6 saat kalanlarda taburculuk sonrası 30 günlük ölüm olasılığı yaklaşık 1,6 kat, 9 saatte 1,9 kat, 12 saatte 2,1 kat (%95 GA 2,02-2,28) yükselmiş.",
      yazarlar: "Aston H. ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.017",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.017"
    },
    {
      baslik: "Hastane Dışı İnme Yönlendirmesine Hastane Performansının Dâhil Edilmesi: Bir Simülasyon Çalışması",
      baslik_en: "Inclusion of Hospital Performance in Prehospital Stroke Routing: A Simulation Study",
      dergi: "Prehosp Emerg Care",
      tarih: "7 Tem 2026",
      tarih_iso: "2026-07-07",
      kategori: "noroloji",
      kategori_etiket: "Nöroloji",
      tur: "Araştırma",
      ozet: "400.000 hasta-konum senaryosunda, olası inme hastalarının yönlendirilmesinde hastane kapı-iğne ve kapı-ponksiyon sürelerini hesaba katan model, AHA uzlaşı önerilerine göre hedefleri %63'e varan oranda değiştirerek hastaları daha hızlı reperfüzyon yapan merkezlere yönlendirmiş.",
      yazarlar: "Zachrison KS. ve ark.",
      doi: "10.1080/10903127.2026.2689666",
      link: "https://doi.org/10.1080/10903127.2026.2689666"
    },
    {
      baslik: "Acil Serviste Evsiz Bireylerde Hepatit C Taraması: DETECT Hep C Çalışmasının İkincil Analizi",
      baslik_en: "Hepatitis C Screening Among Persons Experiencing Homelessness in the Emergency Department: A Secondary Analysis of the Determining Effective Testing in Emergency Departments and Care Coordination on Treatment Outcomes (DETECT) for Hepatitis C (Hep C) Screening Trial",
      dergi: "Ann Emerg Med",
      tarih: "6 Tem 2026",
      tarih_iso: "2026-07-06",
      kategori: "enfeksiyon",
      kategori_etiket: "Enfeksiyon",
      tur: "Araştırma",
      ozet: "67.223 acil servis ziyaretini kapsayan analizde, hedefsiz taramada evsizlik test kabulü ile ilişkiliydi (aRR 1,31); evsizlik HCV seropozitifliği (aRR 2,07-2,91) ve viremi (aRR 3,33-3,70) ile belirgin biçimde ilişkili bulundu.",
      yazarlar: "Joseph KM. ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.009",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.009"
    },
    {
      baslik: "Acil Hekimi Tarafından Yapılan Uyanık Entübasyonların Sıklığı ve Sonuçları: Havayolu Girişimleri Kayıt Verisi",
      baslik_en: "Incidence and Outcomes of Emergency Physician-Performed Awake Intubations: A Report From the Airway Interventions Registry and Observational Database",
      dergi: "Ann Emerg Med",
      tarih: "6 Tem 2026",
      tarih_iso: "2026-07-06",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "Akademik bir acil serviste taranan 1.213 entübasyonun 87'si (%7,2) acil hekimince yapılan ilk girişim uyanık entübasyondu; olguların çoğunda zor havayolu öngörücüleri vardı. Majör olumsuz olay olmaksızın başarı %92, ilk geçiş başarısı %71 idi.",
      yazarlar: "Parks A. ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.007",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.007"
    },
    {
      baslik: "Spontan Dolaşımın Dönüşü Sonrası Erken Sedasyon ve Hastane Öncesi Nakil: AfterROSC1 ve 2 Analizi",
      baslik_en: "Sedation Early After Return of Spontaneous Circulation and During Pre-Hospital Transport After Out-Of-Hospital Cardiac Arrest: Retrospective Analysis of the AfterROSC1 & 2 Database",
      dergi: "Resuscitation",
      tarih: "4 Tem 2026",
      tarih_iso: "2026-07-04",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "1.596 kardiyak arrest sonrası hastanın %83'üne yoğun bakım öncesi sedasyon uygulanmış; 90. günde iyi nörolojik sonuç sedasyonla daha sık görüldü (%32,4'e karşı %11,8) ve düzeltme sonrası ilişki sürdü (aOR 2,19), ancak eğilim skoru düzeltmesinde anlamlılık yitirildi.",
      yazarlar: "Preaubert J. ve ark.",
      doi: "10.1016/j.resuscitation.2026.111196",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111196"
    },
    {
      baslik: "İntranazal Ketamin Çocuklarda Yeterli İşlemsel Sedasyon Sağlar mı?",
      baslik_en: "Is there evidence that intranasal ketamine can provide adequate procedural sedation in paediatric patients?",
      dergi: "Emerg Med J",
      tarih: "3 Tem 2026",
      tarih_iso: "2026-07-03",
      kategori: "pediatri",
      kategori_etiket: "Pediatrik Acil",
      tur: "Derleme",
      ozet: "Sekiz çalışmayı değerlendiren kanıt derlemesi, çocuklarda işlemsel sedasyonda intranazal ketaminin İV yola göre başarı olasılığının biraz düşük olduğunu, ancak iğneden korkan çocuklarda ortak karar alarak düşünülebilecek değerli, iğnesiz bir alternatif sunduğunu bildiriyor.",
      yazarlar: "Jeyabelen H., Manak I.",
      doi: "10.1136/emermed-2026-216136",
      link: "https://doi.org/10.1136/emermed-2026-216136"
    },
    {
      baslik: "Kardiyopulmoner Resüsitasyon Sırasında Hacim Kontrollü Mekanik Ventilasyon: Sistematik Derleme ve Meta-analiz",
      baslik_en: "Volume-controlled mechanical ventilation during cardiopulmonary resuscitation: A systematic review and meta-analysis",
      dergi: "Resuscitation",
      tarih: "3 Tem 2026",
      tarih_iso: "2026-07-03",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Sistematik Derleme",
      ozet: "13 çalışmayı (6 randomize, 461 hasta) içeren derlemede, iki randomize çalışmadan 120 hastanın meta-analizinde hacim kontrollü ile manuel ventilasyon arasında spontan dolaşımın geri dönüşü açısından fark bulunmadı (OR 1,31; %95 GA 0,64-2,71); kanıt kesinliği çok düşük-düşüktü.",
      yazarlar: "Wittig J. ve ark.",
      doi: "10.1016/j.resuscitation.2026.111199",
      link: "https://doi.org/10.1016/j.resuscitation.2026.111199"
    },
    {
      baslik: "Nitazen Aşırı Dozlarında Yüksek Doz Nalokson Gerekir mi?",
      baslik_en: "Are high doses of naloxone required for nitazene overdoses?",
      dergi: "Emerg Med J",
      tarih: "2 Tem 2026",
      tarih_iso: "2026-07-02",
      kategori: "toksikoloji",
      kategori_etiket: "Toksikoloji",
      tur: "Derleme",
      ozet: "Beş çalışmayı değerlendiren kanıt derlemesi, nitazen aşırı dozlarında 0,4-4,4 mg naloksonun yeterli olduğunu ve rutin yüksek doz kullanımını desteklemediğini bildiriyor; doz sıklığı için ek araştırma gerekiyor.",
      yazarlar: "Blanksby I., Harrison L.",
      doi: "10.1136/emermed-2026-216211",
      link: "https://doi.org/10.1136/emermed-2026-216211"
    },
    {
      baslik: "Hastane Öncesi Pediatrik Kan Transfüzyonu Programları İçin En Uygun Hedef Hastalar ve Ekipler",
      baslik_en: "Characterizing pediatric trauma patients and EMS agencies that are optimal targets for prehospital pediatric blood transfusion programs",
      dergi: "Prehosp Emerg Care",
      tarih: "2 Tem 2026",
      tarih_iso: "2026-07-02",
      kategori: "travma",
      kategori_etiket: "Travma",
      tur: "Araştırma",
      ozet: "2021-2024 NEMSIS verisinde 2,49 milyon yaralı çocuğun %1,37'si fizyolojik ölçütlerle transfüzyona uygunken, kan ürünü yalnızca uygun olguların %1,01'ine verilmiş; ekiplerin sadece %1,4'ü çocuklara transfüzyon yapıyor ve uygun hastalar çoğunlukla kırsal, ileri yaşam desteği veren ekiplerce taşınıyor.",
      yazarlar: "Ramgopal S., Martin-Gill C.",
      doi: "10.1080/10903127.2026.2696013",
      link: "https://doi.org/10.1080/10903127.2026.2696013"
    },
    {
      baslik: "Pediatrik Acilde Yatak Başı Ultrason Rehberliğinde Hidrostatik İnvajinasyon Redüksiyonu",
      baslik_en: "Point-of-Care Ultrasound-Guided Hydrostatic Reduction of Ileocolic Intussusception in the Pediatric Emergency Department",
      dergi: "Ann Emerg Med",
      tarih: "2 Tem 2026",
      tarih_iso: "2026-07-02",
      kategori: "pediatri",
      kategori_etiket: "Pediatrik Acil",
      tur: "Olgu Serisi",
      ozet: "3-36 aylık 9 çocukta acil hekimince yatak başı ultrason rehberliğinde yapılan hidrostatik redüksiyon 8/9 olguda (%88,9) başarılı olmuş; ortanca varıştan redüksiyona süre 1,69 saat olup komplikasyon ve 24 saatte nüks görülmemiş, tek başarısızlıkta cerrahi öncü nokta vardı.",
      yazarlar: "Zymerman SA. ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.006",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.006"
    },
    {
      baslik: "Pediatrik Hastane Dışı Kardiyak Arrest Sonuçlarında Irk, Kentleşme ve Yoksullukla İlişkili Eşitsizlikler: NEMSIS Çalışması",
      baslik_en: "Disparities in Pediatric Out-of-Hospital Cardiac Arrest Outcomes Relating to Race, Urbanicity, and Poverty: A Study of the NEMSIS Database",
      dergi: "Prehosp Emerg Care",
      tarih: "1 Tem 2026",
      tarih_iso: "2026-07-01",
      kategori: "resusitasyon",
      kategori_etiket: "Resüsitasyon",
      tur: "Araştırma",
      ozet: "14.783 pediatrik hastane dışı kardiyak arrest olgusunda, beyaz çocuklara kıyasla siyahi çocuklar daha az tanık KPR'si (OR 0,72) ve daha düşük spontan dolaşım dönüşü (OR 0,71) yaşadı; yüksek toplumsal yoksulluk da daha düşük KPR, OED kullanımı ve ROSC ile ilişkiliydi.",
      yazarlar: "Bernardin ME. ve ark.",
      doi: "10.1080/10903127.2026.2695249",
      link: "https://doi.org/10.1080/10903127.2026.2695249"
    },
    {
      baslik: "Düşük Riskli Triyajlı Travma Dışı Hastalarda Hastane Öncesi Fizyolojik İnstabilite ve Hastane İçi Mortalite",
      baslik_en: "Prehospital physiologic instability and in-hospital mortality among non-trauma patients with low-risk emergency department triage",
      dergi: "Prehosp Emerg Care",
      tarih: "1 Tem 2026",
      tarih_iso: "2026-07-01",
      kategori: "klinik-karar",
      kategori_etiket: "Klinik Karar",
      tur: "Araştırma",
      ozet: "13 acil servise taşınan 86.069 düşük riskli triyajlı travma dışı erişkinde, hastane öncesi NEWS skoru yükseldikçe hastane içi mortalite arttı (%1,2'den %6,8'e); orta ve yüksek hastane öncesi risk sırasıyla 1,93 ve 4,10 kat mortalite ile ilişkiliydi.",
      yazarlar: "Lee SGW. ve ark.",
      doi: "10.1080/10903127.2026.2695257",
      link: "https://doi.org/10.1080/10903127.2026.2695257"
    },
    {
      baslik: "İğne Torakostomi: Göğüs Duvarı Kalınlığının Anatomik Bölge ve İğne Uzunluğu Açısından Önemi",
      baslik_en: "Needle Thoracostomy: Implications of Chest Wall Thickness for Anatomical Location and Needle Length",
      dergi: "Ann Emerg Med",
      tarih: "1 Tem 2026",
      tarih_iso: "2026-07-01",
      kategori: "travma",
      kategori_etiket: "Travma",
      tur: "Araştırma",
      ozet: "Sınıf II-III obezitesi olan 110 hastada ultrasonla ölçülen göğüs duvarı kalınlığı, 2. interkostal aralık midklavikuler hatta olguların %22'sinde 50 mm'yi aşarken 4/5. interkostal ön aksiller hatta %82'sinde aştı; bu da iğne dekompresyonunda bölge ve iğne uzunluğu seçiminin önemini vurguluyor.",
      yazarlar: "Schaefer L. ve ark.",
      doi: "10.1016/j.annemergmed.2026.06.014",
      link: "https://doi.org/10.1016/j.annemergmed.2026.06.014"
    },
    {
      baslik: "Kadın Acil Hekimleri: Girişten Yükselmeye Cinsiyet Eşitsizlikleri",
      baslik_en: "Women Emergency Physicians and Gender Disparities from Entry to Advancement",
      dergi: "Ann Emerg Med",
      tarih: "1 Tem 2026",
      tarih_iso: "2026-07-01",
      kategori: "sistem",
      kategori_etiket: "Sistem & Meslek",
      tur: "Kapsam Derlemesi",
      ozet: "2003-2024 arası 191 çalışmayı kapsayan kapsam derlemesi, kadın acil hekimlerinin temsili, yazarlık ve ödüllerde iyileşme olsa da ücret, editör kurulu üyeliği, üst düzey liderlik ve akademik unvanda süregelen eşitsizliklere işaret ediyor.",
      yazarlar: "Sethuraman KN. ve ark.",
      doi: "10.1016/j.annemergmed.2026.04.012",
      link: "https://doi.org/10.1016/j.annemergmed.2026.04.012"
    },
    {
      baslik: "Acil Serviste Baş Dönmesinde Görüntüleme ve Sevkleri Optimize Eden Makine Öğrenmesi Modelleri",
      baslik_en: "Development and Validation of Machine Learning Models to Optimize Imaging and Referrals for Dizziness in the Emergency Department",
      dergi: "Acad Emerg Med",
      tarih: "1 Tem 2026",
      tarih_iso: "2026-07-01",
      kategori: "klinik-karar",
      kategori_etiket: "Klinik Karar",
      tur: "Doğrulama Çalışması",
      ozet: "Baş dönmesi olan 6.637 hastada geliştirilen dört makine öğrenmesi modeli, 30 gün içindeki ciddi tanıları (inme, GİA, diseksiyon, tümör) güçlü biçimde ayırt etti (AUC 0,92-0,97); LASSO modeli %97 duyarlılıkla BT ve sevklerde belirgin azalma öngördü.",
      yazarlar: "Roy DC. ve ark.",
      doi: "10.1111/acem.70369",
      link: "https://doi.org/10.1111/acem.70369"
    }
  ]
};
